version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /home/containters/nginxssl/nginx/conf/:/etc/nginx/conf.d/:ro
      - /home/containters/nginxssl/certbot/www:/var/www/certbot/:ro
      - /home/containters/nginxssl/certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /home/containters/nginxssl/certbot/www/:/var/www/certbot/:rw
      - /home/containters/nginxssl/certbot/conf/:/etc/letsencrypt/:rw
